config/routes.rb
QuestionAnswer::Application.routes.draw do

  devise_for :users

  resources :questions do
    resources :answers, :only => %w(new create edit)
  end

  resources :answers

  root :to => "questions#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)

    if user.admin?
      can :modify, :all
    else
      can :modify, Question do |question|
        user == question.try(:user)
      end
      can :modify, Answer do |answer|
        user == answer.try(:user)
      end
    end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :body, :question_id, :user_id

  belongs_to :question
  belongs_to :user

  validates_presence_of :body, :question_id, :user_id
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :body, :title, :user_id

  belongs_to :user
  has_many :answers

  has_many :rate_limits, :foreign_key => "issue_id"

  validates_presence_of :title, :body, :user_id

  def self.search(query)
    where("title LIKE ?", "%#{query}%")
  end
end

app/models/rate_limit.rb
class RateLimit < ActiveRecord::Base
  attr_accessible :issue_id, :owner_id

  belongs_to :user
  belongs_to :question
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body


  has_many :questions
  has_many :answers
  has_many :rate_limits, :foreign_key => "owner_id"

  def admin?
    role == 'admin'
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  before_filter :authenticate_user!
  before_filter :fetch_answer, :only => [:update, :edit, :destroy]
  before_filter :redirect_if_cannot_modify, :only => [:update, :destroy, :edit]

  def new
    @answer = Answer.new(:question_id => params[:question_id])
  end

  def create
    @answer = Answer.create(params[:answer].merge({user_id: current_user.id}))

    if @answer.id
      redirect_to question_path(@answer.question)
    else
      flash.now[:notice] = "Can't be blank"
      render :action => "new"
    end
  end

  def update
    @answer.update_attributes(params[:answer])
    redirect_to question_path(@answer.question)
  end

  def destroy
    @answer.destroy
    redirect_to question_path(@answer.question)
  end

  private

  def fetch_answer
    @answer = Answer.find_by_id(params[:id])
  end

  def redirect_if_cannot_modify
    redirect_to root_path if cannot?(:modify, @answer)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :authenticate_user!, except: %w(show index)

  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_filter :authenticate_user!, :except => [:show, :index]
  before_filter :fetch_question, :only => [:update, :show, :edit, :destroy]
  before_filter :redirect_if_cannot_modify, :only => [:destroy, :edit]

  def new
    @question = Question.new
  end
  
  def create

    @question = Question.create(params[:question].merge({user_id: current_user.id}))
    if @question.id
      render :action => "show"
    else
      flash.now[:notice] = "Can't be blank"
      render :action => "new"
    end
  end

  def update
    if params[:rate]
      if RateLimit.where(:owner_id => current_user.id, :issue_id => @question.id).first
        flash[:notice] = "You have entered a rating for this question"
      else
        @question.rate_limits.create(:owner_id => current_user.id, :issue_id => @question.id)
        @question.update_attribute("rate", @question.rate + params[:rate].to_i) if (-6 < params[:rate].to_i) && (params[:rate].to_i < 6)
      end
    else
      @question.update_attributes(params[:question])
    end
    redirect_to question_path(@question)
  end

  def show
    @answers = @question.answers
  end

  def index
    @questions = case
      when params[:by_rate]
        Question.order("rate").last(10)
      when params[:by_answers]
        Question.joins("LEFT JOIN `answers` ON `questions`.id = answers.question_id").group("questions.id").order("COUNT(answers.id)").last(10)
      when params[:commit]
        Question.search(params[:query])
      else
        Question.last(10)
    end
  end

  def destroy
    @question.destroy and redirect_to questions_path
  end

  private

  def fetch_question
    @question = Question.find_by_id(params[:id])
  end

  def redirect_if_cannot_modify
    redirect_to root_path if cannot?(:modify, @question)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.haml
%tr
  %td
    = answer.body
  %td.first
    - if can?(:modify, answer)
      = link_to "Edit answer", edit_question_answer_path(@question, answer)
      = link_to "Delete answer", answer_path(answer), :method => :delete

app/views/answers/_form_for_answer.html.haml
= form_for @answer do |form|
  = form.hidden_field :question_id
  .answer_field
    = form.text_area :body
  .actions
    = form.submit

= link_to "back", question_path(@answer.question)

app/views/answers/edit.html.haml
#answer.title
  Edit answer

#answer.form
  = render partial: "form_for_answer"

app/views/answers/new.html.haml
#answer.title
  Here you can post answer

#answer.form
  = render partial: "form_for_answer"

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Teachme
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .navigation
      - if signed_in?
        %span
          = "Signed in as #{current_user.email}"
        %span
          = link_to 'Sign out', destroy_user_session_path, method: 'delete'
      - else
        %span
          = link_to 'Sign in', new_user_session_path
        %span
          = link_to 'Sign up', new_user_registration_path
    .flash
      = flash[:error]
      = flash[:notice]
    = yield

app/views/questions/_form_for_question.html.haml
= form_for @question do |form|
  .name
    Question title
  .question_field
    = form.text_field :title
  .question_field
    = form.text_area :body
  .actions
    = form.submit

app/views/questions/_question.html.haml
.question
  %table#table
    %tr
      %td.second
        = link_to truncate(question.title, :length => 30), question_path(question.id), :class => "question_link"
      %td.first
        Rating:
        = question.rate
      %td.first
        Answers:
        = question.answers.count

app/views/questions/edit.html.haml
#question.title
  Edit question

#question.form
  = render partial: "form_for_question"
  = link_to "back", question_path(@question.id)

app/views/questions/index.html.haml
#questions
  .page-header
    %h1 Questions
  .links
    = link_to "New question", new_question_path
    %br
    Sort:
    =link_to "by rate", questions_path(:by_rate => 1)
    ,
    =link_to "by answers", questions_path(:by_answers => 1)
    ,
    =link_to "last 10", questions_path
    = form_tag questions_path, :method => "get" do
      = text_field_tag  'query'
      = submit_tag "search"
  #all_questions
    = render @questions.reverse

app/views/questions/new.html.haml
#question.title
  Here you can post question

#question.form

  = render partial: "form_for_question"
  = link_to "back", :back

app/views/questions/show.html.haml
%table#table2
  %tr
    %td.first
      Title:
    %td
      = @question.title
  %tr
    %td.first
      Question:
    %td
      = @question.body
  %tr
    %td.first
      Rating:
    %td
      = @question.rate
  %tr
    %td.first
      Set rating:
    %td
      = form_tag question_path(@question), :method => "put" do
        = select_tag "rate", options_for_select((-5..5), :selected => 0)
        = submit_tag "set"

%div
  %br
  Answers:
  - if @answers
    %table#table3
      = render @answers

%div
  %br
  = link_to "New answer", new_question_answer_path(@question)
  = link_to "All questions", questions_path
  - if can?(:modify, @question)
    = link_to "Edit question", edit_question_path(@question)
    = link_to "Delete question", question_path(@question), :method => :delete